version: '3.9'

services:

  backend:
    build:
      context: .
      dockerfile: ${PWD}/docker/django/Dockerfile.dev
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - 8000:8000
    command: sh scripts/run_dev.sh

  redis:
    image: redis:7-alpine
