version: '3.9'

services:

  backend:
    build:
      context: .
      dockerfile: ${PWD}/docker/django/Dockerfile
    env_file:
      - .env
    ports:
      - 8000:8000
    command: sh scripts/entrypoint_prod.sh

  redis:
    image: redis:7-alpine
