name: CI 


on:
  pull_request:
    branches:
      - main


jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Create .env file
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_SECRET_KEY: ${{ secrets.SECRET_KEY }}
          envkey_ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS }}
          envkey_DB_ENGINE: ${{ secrets.DB_ENGINE }}
          envkey_CHANNEL_LAYER_BACKEND: ${{ secrets.CHANNEL_LAYER_BACKEND }}
          envkey_REDIS_SERVER: ${{ secrets.REDIS_SERVER }}
          envkey_REDIS_PORT: ${{ secrets.REDIS_PORT }}

      - name: Build image with docker compose
        run: |
          ls -al
          docker compose build --no-cache

  test:
    runs-on:  ubuntu-latest
    needs:  build

    steps:
      - name: Run test in docker container
        run:  docker compose run --rm backend pytest