name: CI 


on:
  pull_request:
    branches:
      - main


jobs:

  create-envfile:
    runs-on: ubuntu-latest

    steps:
      - name: Create .env file
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_SECRET_KEY: ${{ secrets.SECRET_KEY }}
          envkey_ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS }}
          envkey_DB_ENGINE: ${{ secrets.DB_ENGINE }}
          envkey_CHANNEL_LAYER_BACKEND: ${{ secrets.CHANNEL_LAYER_BACKEND }}
          envkey_REDIS_SERVER: ${{ secrets.REDIS_SERVER }}
          envkey_REDIS_PORT: ${{ secrets.REDIS_PORT }}

  build:
    runs-on: ubuntu-latest
    needs: create-envfile

    steps:
      - name: Checkout codebase
        uses: actions/checkout@v3

      - name: Build image with docker compose
        run:  docker compose -f docker-compose.yml build --no-cache

  test:
    runs-on:  ubuntu-latest
    needs:
      - create-envfile
      - build

    steps:
      - name: Run test in docker container
        run:  docker compose -f docker-compose.yml run --rm backend pytest