name: CI 


on:
  pull_request:
    branches:
      - main


jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codebase
        uses: actions/checkout@v3

      - name: Build image with docker compose
        run:  docker compose -f docker-compose.yml build --no-cache

  test:
    runs-on:  ubuntu-latest
    needs: build

    steps:
      - name: Run test in docker container
        run:  docker compose -f docker-compose.yml run --rm backend pytest